// Mocks generated by Mockito 5.2.0 from annotations
// in ax_dapp/test/buy_dialog_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i9;
import 'dart:ui' as _i15;

import 'package:ax_dapp/repositories/subgraph/usecases/get_buy_info_use_case.dart'
    as _i10;
import 'package:ax_dapp/service/controller/controller.dart' as _i5;
import 'package:ax_dapp/service/controller/swap/swap_controller.dart' as _i12;
import 'package:ax_dapp/service/controller/token.dart' as _i13;
import 'package:ax_dapp/service/controller/usecases/get_max_token_input_use_case.dart'
    as _i11;
import 'package:ax_dapp/service/controller/wallet_controller.dart' as _i4;
import 'package:ethereum_api/ethereum_api.dart' as _i2;
import 'package:fpdart/fpdart.dart' as _i3;
import 'package:get/get.dart' as _i6;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tokens_repository/src/tokens_repository.dart' as _i8;
import 'package:web3dart/web3dart.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAptPair_0 extends _i1.Fake implements _i2.AptPair {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

class _FakeWalletController_2 extends _i1.Fake implements _i4.WalletController {
}

class _FakeController_3 extends _i1.Fake implements _i5.Controller {}

class _FakeRx_4<T> extends _i1.Fake implements _i6.Rx<T> {}

class _FakeRxString_5 extends _i1.Fake implements _i6.RxString {}

class _FakeRxDouble_6 extends _i1.Fake implements _i6.RxDouble {}

class _FakeEthereumAddress_7 extends _i1.Fake implements _i7.EthereumAddress {}

class _FakeBigInt_8 extends _i1.Fake implements BigInt {}

class _FakeInternalFinalCallback_9<T> extends _i1.Fake
    implements _i6.InternalFinalCallback<T> {}

/// A class which mocks [TokensRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokensRepository extends _i1.Mock implements _i8.TokensRepository {
  MockTokensRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Stream<List<_i2.Token>> get tokensChanges =>
      (super.noSuchMethod(Invocation.getter(#tokensChanges),
              returnValue: Stream<List<_i2.Token>>.empty())
          as _i9.Stream<List<_i2.Token>>);
  @override
  List<_i2.Token> get tokens => (super.noSuchMethod(Invocation.getter(#tokens),
      returnValue: <_i2.Token>[]) as List<_i2.Token>);
  @override
  _i9.Stream<List<_i2.Apt>> get aptsChanges => (super.noSuchMethod(
      Invocation.getter(#aptsChanges),
      returnValue: Stream<List<_i2.Apt>>.empty()) as _i9.Stream<List<_i2.Apt>>);
  @override
  List<_i2.Apt> get apts =>
      (super.noSuchMethod(Invocation.getter(#apts), returnValue: <_i2.Apt>[])
          as List<_i2.Apt>);
  @override
  _i9.Stream<_i2.AptPair> aptPairChanges(int? athleteId) =>
      (super.noSuchMethod(Invocation.method(#aptPairChanges, [athleteId]),
          returnValue: Stream<_i2.AptPair>.empty()) as _i9.Stream<_i2.AptPair>);
  @override
  _i2.AptPair aptPair(int? athleteId) =>
      (super.noSuchMethod(Invocation.method(#aptPair, [athleteId]),
          returnValue: _FakeAptPair_0()) as _i2.AptPair);
  @override
  void switchTokens(_i2.EthereumChain? chain) =>
      super.noSuchMethod(Invocation.method(#switchTokens, [chain]),
          returnValueForMissingStub: null);
}

/// A class which mocks [GetBuyInfoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBuyInfoUseCase extends _i1.Mock implements _i10.GetBuyInfoUseCase {
  MockGetBuyInfoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i3.Either<_i10.Success, _i10.Error>> fetchAptBuyInfo(
          {String? aptAddress, double? axInput}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchAptBuyInfo, [],
                  {#aptAddress: aptAddress, #axInput: axInput}),
              returnValue: Future<_i3.Either<_i10.Success, _i10.Error>>.value(
                  _FakeEither_1<_i10.Success, _i10.Error>()))
          as _i9.Future<_i3.Either<_i10.Success, _i10.Error>>);
}

/// A class which mocks [GetTotalTokenBalanceUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTotalTokenBalanceUseCase extends _i1.Mock
    implements _i11.GetTotalTokenBalanceUseCase {
  MockGetTotalTokenBalanceUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.WalletController get walletController =>
      (super.noSuchMethod(Invocation.getter(#walletController),
          returnValue: _FakeWalletController_2()) as _i4.WalletController);
  @override
  _i9.Future<double> getTotalAxBalance() =>
      (super.noSuchMethod(Invocation.method(#getTotalAxBalance, []),
          returnValue: Future<double>.value(0.0)) as _i9.Future<double>);
  @override
  _i9.Future<double> getTotalBalanceForToken(String? tokenAddress) => (super
      .noSuchMethod(Invocation.method(#getTotalBalanceForToken, [tokenAddress]),
          returnValue: Future<double>.value(0.0)) as _i9.Future<double>);
}

/// A class which mocks [SwapController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSwapController extends _i1.Mock implements _i12.SwapController {
  MockSwapController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Controller get controller =>
      (super.noSuchMethod(Invocation.getter(#controller),
          returnValue: _FakeController_3()) as _i5.Controller);
  @override
  set controller(_i5.Controller? _controller) =>
      super.noSuchMethod(Invocation.setter(#controller, _controller),
          returnValueForMissingStub: null);
  @override
  _i6.Rx<_i13.Token> get activeTkn1 =>
      (super.noSuchMethod(Invocation.getter(#activeTkn1),
          returnValue: _FakeRx_4<_i13.Token>()) as _i6.Rx<_i13.Token>);
  @override
  set activeTkn1(_i6.Rx<_i13.Token>? _activeTkn1) =>
      super.noSuchMethod(Invocation.setter(#activeTkn1, _activeTkn1),
          returnValueForMissingStub: null);
  @override
  _i6.Rx<_i13.Token> get activeTkn2 =>
      (super.noSuchMethod(Invocation.getter(#activeTkn2),
          returnValue: _FakeRx_4<_i13.Token>()) as _i6.Rx<_i13.Token>);
  @override
  set activeTkn2(_i6.Rx<_i13.Token>? _activeTkn2) =>
      super.noSuchMethod(Invocation.setter(#activeTkn2, _activeTkn2),
          returnValueForMissingStub: null);
  @override
  _i6.RxString get address1 => (super.noSuchMethod(Invocation.getter(#address1),
      returnValue: _FakeRxString_5()) as _i6.RxString);
  @override
  set address1(_i6.RxString? _address1) =>
      super.noSuchMethod(Invocation.setter(#address1, _address1),
          returnValueForMissingStub: null);
  @override
  _i6.RxString get address2 => (super.noSuchMethod(Invocation.getter(#address2),
      returnValue: _FakeRxString_5()) as _i6.RxString);
  @override
  set address2(_i6.RxString? _address2) =>
      super.noSuchMethod(Invocation.setter(#address2, _address2),
          returnValueForMissingStub: null);
  @override
  _i6.RxDouble get amount1 => (super.noSuchMethod(Invocation.getter(#amount1),
      returnValue: _FakeRxDouble_6()) as _i6.RxDouble);
  @override
  set amount1(_i6.RxDouble? _amount1) =>
      super.noSuchMethod(Invocation.setter(#amount1, _amount1),
          returnValueForMissingStub: null);
  @override
  _i6.RxDouble get amount2 => (super.noSuchMethod(Invocation.getter(#amount2),
      returnValue: _FakeRxDouble_6()) as _i6.RxDouble);
  @override
  set amount2(_i6.RxDouble? _amount2) =>
      super.noSuchMethod(Invocation.setter(#amount2, _amount2),
          returnValueForMissingStub: null);
  @override
  _i6.RxDouble get price => (super.noSuchMethod(Invocation.getter(#price),
      returnValue: _FakeRxDouble_6()) as _i6.RxDouble);
  @override
  set price(_i6.RxDouble? _price) =>
      super.noSuchMethod(Invocation.setter(#price, _price),
          returnValueForMissingStub: null);
  @override
  _i7.EthereumAddress get routerTestnetAddress =>
      (super.noSuchMethod(Invocation.getter(#routerTestnetAddress),
          returnValue: _FakeEthereumAddress_7()) as _i7.EthereumAddress);
  @override
  _i7.EthereumAddress get dexTestnetAddress =>
      (super.noSuchMethod(Invocation.getter(#dexTestnetAddress),
          returnValue: _FakeEthereumAddress_7()) as _i7.EthereumAddress);
  @override
  _i7.EthereumAddress get routerMainnetAddress =>
      (super.noSuchMethod(Invocation.getter(#routerMainnetAddress),
          returnValue: _FakeEthereumAddress_7()) as _i7.EthereumAddress);
  @override
  _i7.EthereumAddress get dexMainnetAddress =>
      (super.noSuchMethod(Invocation.getter(#dexMainnetAddress),
          returnValue: _FakeEthereumAddress_7()) as _i7.EthereumAddress);
  @override
  _i7.EthereumAddress get axtAddress =>
      (super.noSuchMethod(Invocation.getter(#axtAddress),
          returnValue: _FakeEthereumAddress_7()) as _i7.EthereumAddress);
  @override
  BigInt get twoMinuteDeadline =>
      (super.noSuchMethod(Invocation.getter(#twoMinuteDeadline),
          returnValue: _FakeBigInt_8()) as BigInt);
  @override
  _i6.Rx<BigInt> get deadline =>
      (super.noSuchMethod(Invocation.getter(#deadline),
          returnValue: _FakeRx_4<BigInt>()) as _i6.Rx<BigInt>);
  @override
  set deadline(_i6.Rx<BigInt>? _deadline) =>
      super.noSuchMethod(Invocation.setter(#deadline, _deadline),
          returnValueForMissingStub: null);
  @override
  BigInt get amountOutMin =>
      (super.noSuchMethod(Invocation.getter(#amountOutMin),
          returnValue: _FakeBigInt_8()) as BigInt);
  @override
  set amountOutMin(BigInt? _amountOutMin) =>
      super.noSuchMethod(Invocation.setter(#amountOutMin, _amountOutMin),
          returnValueForMissingStub: null);
  @override
  double get x =>
      (super.noSuchMethod(Invocation.getter(#x), returnValue: 0.0) as double);
  @override
  set x(double? _x) => super
      .noSuchMethod(Invocation.setter(#x, _x), returnValueForMissingStub: null);
  @override
  double get y =>
      (super.noSuchMethod(Invocation.getter(#y), returnValue: 0.0) as double);
  @override
  set y(double? _y) => super
      .noSuchMethod(Invocation.setter(#y, _y), returnValueForMissingStub: null);
  @override
  double get k =>
      (super.noSuchMethod(Invocation.getter(#k), returnValue: 0.0) as double);
  @override
  set k(double? _k) => super
      .noSuchMethod(Invocation.setter(#k, _k), returnValueForMissingStub: null);
  @override
  _i6.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(Invocation.getter(#onStart),
              returnValue: _FakeInternalFinalCallback_9<void>())
          as _i6.InternalFinalCallback<void>);
  @override
  _i6.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(Invocation.getter(#onDelete),
              returnValue: _FakeInternalFinalCallback_9<void>())
          as _i6.InternalFinalCallback<void>);
  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);
  @override
  _i9.Future<void> approve() =>
      (super.noSuchMethod(Invocation.method(#approve, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> swap() => (super.noSuchMethod(Invocation.method(#swap, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> createPair() =>
      (super.noSuchMethod(Invocation.method(#createPair, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> swapforAX() =>
      (super.noSuchMethod(Invocation.method(#swapforAX, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> swapFromAX() =>
      (super.noSuchMethod(Invocation.method(#swapFromAX, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  void updateFromAmount(double? newAmount) =>
      super.noSuchMethod(Invocation.method(#updateFromAmount, [newAmount]),
          returnValueForMissingStub: null);
  @override
  void updateToAmount(double? newAmount) =>
      super.noSuchMethod(Invocation.method(#updateToAmount, [newAmount]),
          returnValueForMissingStub: null);
  @override
  void updateFromAddress(String? newAddress) =>
      super.noSuchMethod(Invocation.method(#updateFromAddress, [newAddress]),
          returnValueForMissingStub: null);
  @override
  void updateToAddress(String? newAddress) =>
      super.noSuchMethod(Invocation.method(#updateToAddress, [newAddress]),
          returnValueForMissingStub: null);
  @override
  void updatePrice() => super.noSuchMethod(Invocation.method(#updatePrice, []),
      returnValueForMissingStub: null);
  @override
  void updateFromToken(_i13.Token? tknFrom) =>
      super.noSuchMethod(Invocation.method(#updateFromToken, [tknFrom]),
          returnValueForMissingStub: null);
  @override
  void updateToToken(_i13.Token? tknTo) =>
      super.noSuchMethod(Invocation.method(#updateToToken, [tknTo]),
          returnValueForMissingStub: null);
  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(Invocation.method(#update, [ids, condition]),
          returnValueForMissingStub: null);
  @override
  void onInit() => super.noSuchMethod(Invocation.method(#onInit, []),
      returnValueForMissingStub: null);
  @override
  void onReady() => super.noSuchMethod(Invocation.method(#onReady, []),
      returnValueForMissingStub: null);
  @override
  void onClose() => super.noSuchMethod(Invocation.method(#onClose, []),
      returnValueForMissingStub: null);
  @override
  void $configureLifeCycle() =>
      super.noSuchMethod(Invocation.method(#$configureLifeCycle, []),
          returnValueForMissingStub: null);
  @override
  _i14.Disposer addListener(_i14.GetStateUpdate? listener) =>
      (super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValue: () {}) as _i14.Disposer);
  @override
  void removeListener(_i15.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void refresh() => super.noSuchMethod(Invocation.method(#refresh, []),
      returnValueForMissingStub: null);
  @override
  void refreshGroup(Object? id) =>
      super.noSuchMethod(Invocation.method(#refreshGroup, [id]),
          returnValueForMissingStub: null);
  @override
  void notifyChildrens() =>
      super.noSuchMethod(Invocation.method(#notifyChildrens, []),
          returnValueForMissingStub: null);
  @override
  void removeListenerId(Object? id, _i15.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListenerId, [id, listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  _i14.Disposer addListenerId(Object? key, _i14.GetStateUpdate? listener) =>
      (super.noSuchMethod(Invocation.method(#addListenerId, [key, listener]),
          returnValue: () {}) as _i14.Disposer);
  @override
  void disposeId(Object? id) =>
      super.noSuchMethod(Invocation.method(#disposeId, [id]),
          returnValueForMissingStub: null);
}
